/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#86cbff",
        "on-background": "#2c2f30",
        "on-primary-fixed": "#000000",
        "surface-container-lowest": "#ffffff",
        "error-dim": "#b92902",
        "secondary": "#00618f",
        "surface-container-low": "#eff1f2",
        "surface-container-highest": "#dadddf",
        "secondary-fixed": "#a7d7ff",
        "on-primary-container": "#401600",
        "inverse-primary": "#fd6c00",
        "on-secondary-fixed": "#003855",
        "surface-container": "#e6e8ea",
        "surface-bright": "#f5f6f7",
        "tertiary-container": "#f7b21f",
        "background": "#f5f6f7",
        "secondary-dim": "#00557d",
        "surface-variant": "#dadddf",
        "on-error": "#ffefec",
        "outline-variant": "#abadae",
        "on-tertiary-fixed-variant": "#5b3e00",
        "primary-fixed": "#ff7a2c",
        "error": "#b02500",
        "on-tertiary-fixed": "#342200",
        "surface-tint": "#9b3f00",
        "on-surface": "#2c2f30",
        "tertiary-dim": "#6b4900",
        "on-surface-variant": "#595c5d",
        "tertiary-fixed": "#f7b21f",
        "surface-container-high": "#e0e3e4",
        "on-tertiary-container": "#4f3600",
        "inverse-surface": "#0c0f10",
        "primary": "#9b3f00",
        "surface": "#f5f6f7",
        "outline": "#757778",
        "on-tertiary": "#fff1df",
        "inverse-on-surface": "#9b9d9e",
        "on-primary-fixed-variant": "#4f1d00",
        "primary-dim": "#883700",
        "tertiary": "#7a5400",
        "primary-fixed-dim": "#f46800",
        "on-error-container": "#520c00",
        "surface-dim": "#d1d5d7",
        "on-secondary-fixed-variant": "#00567f",
        "on-secondary": "#eaf4ff",
        "primary-container": "#ff7a2c",
        "error-container": "#f95630",
        "on-secondary-container": "#004c71",
        "secondary-container": "#a7d7ff",
        "on-primary": "#fff0ea",
        "tertiary-fixed-dim": "#e7a407"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
