/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fa",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#a7c8ff",
        "inverse-surface": "#2e3132",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#799dd6",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#1f477b",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6c5000",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5b4300",
        "on-surface": "#191c1d",
        "on-surface-variant": "#43474f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#47aaaa",
        "on-tertiary-fixed": "#002020",
        "on-tertiary-fixed-variant": "#004f4f",
        "outline": "#737780",
        "outline-variant": "#c3c6d1",
        "primary": "#001e40",
        "primary-container": "#003366",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#a7c8ff",
        "secondary": "#785900",
        "secondary-container": "#fdc003",
        "secondary-fixed": "#ffdf9e",
        "secondary-fixed-dim": "#fabd00",
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d9dadb",
        "surface-tint": "#3a5f94",
        "surface-variant": "#e1e3e4",
        "tertiary": "#002323",
        "tertiary-container": "#003a3a",
        "tertiary-fixed": "#93f2f2",
        "tertiary-fixed-dim": "#76d6d5"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      boxShadow: {
        "ambient": "0 0 32px rgba(25, 28, 29, 0.04)"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
